/*
 * Copyright (c) 2018, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
var DEFINES = {
	CLUSTER_CLASS: { 	GENERAL: {}, 
						CLOSURES: {}, 
						HVAC: {}, 
						LIGHTING: {}, 
						MEASUREMENT_SENSING: {}, 
						SECURITY_SAFETY: {}, 
						PROTOCOL_INTERFACE: {} },
	WORK_CODE: {},
	SOURCE_ENDPOINT: {},
	ADDR_MODE: {},
	DIRECTION: {},
	STATUS: {},
	DATA_TYPE: {},
	NV_ITEM_ID: {},
	DEVICETYPE: {},
	PAIRING_STAGE: {},
	CLUSTER_CLASS_ID: {}
};


DEFINES.PAIRING_STAGE = {};
DEFINES.PAIRING_STAGE.SEARCHING					= 1;//Controller in pairing mode, searching for zigbee device
DEFINES.PAIRING_STAGE.FOUND_DEVICE				= 2;//Found a device
DEFINES.PAIRING_STAGE.DEVICE_PAIRED				= 3;//Device paired successfully
DEFINES.PAIRING_STAGE.GET_MANUFACTURER_INFO		= 4;//Get more info about the device
DEFINES.PAIRING_STAGE.INIT_CONTROLLER			= 5;//Start device controller
DEFINES.PAIRING_STAGE.COMMISSIONING_COMPLETE	= 6;//Commissioning process completed successfully
DEFINES.PAIRING_STAGE.ALREADY_BOUND				= 7;//Already bound device
DEFINES.PAIRING_STAGE.FAILED 					= 8;//Commissioning process failed with error
DEFINES.PAIRING_STAGE.DO_NOT_SUPPORT			= 9;//Do not support this type of device
DEFINES.PAIRING_STAGE.INCOMPLETE 				= 10;//Could not complete the process
DEFINES.PAIRING_STAGE.AUTOGEN_CONTROLLER 		= 11;//Creating an autogen controller
DEFINES.PAIRING_STAGE.PERMIT_FAILED 			= 12;//Permit join failed

DEFINES.CLUSTER_CLASS_ID = {
	0: 'basic',
	6: 'on_off',
	8: 'level',
	768: 'color_control',
	513: 'thermostat',
	514: 'fan_control',
	516: 'thermostatUserInterface',
	1026: 'temperature',
	1029: 'relative_humidity',
	1030: 'occupancy_sensor'
};


DEFINES.CLUSTER_CLASS.GENERAL.BASIC										= 0x0000;
DEFINES.CLUSTER_CLASS.GENERAL.POWER_CONFIGURATION						= 0x0001;
DEFINES.CLUSTER_CLASS.GENERAL.DEVICE_TEMPERATURE_CONFIGURATION			= 0x0002;
DEFINES.CLUSTER_CLASS.GENERAL.IDENTIFY									= 0x0003;
DEFINES.CLUSTER_CLASS.GENERAL.GROUPS									= 0x0004;
DEFINES.CLUSTER_CLASS.GENERAL.SCENES									= 0x0005;
DEFINES.CLUSTER_CLASS.GENERAL.ONOFF										= 0x0006;
DEFINES.CLUSTER_CLASS.GENERAL.ONOFF_SWITCH_CONFIGURATION				= 0x0007;
DEFINES.CLUSTER_CLASS.GENERAL.LEVEL_CONTROL								= 0x0008;
DEFINES.CLUSTER_CLASS.GENERAL.ALARMS									= 0x0009;
DEFINES.CLUSTER_CLASS.GENERAL.TIME										= 0x000A;
DEFINES.CLUSTER_CLASS.GENERAL.RSSI_LOCATION								= 0x000B;


DEFINES.CLUSTER_CLASS.LIGHTING.COLOR_CONTROL							= 0x0300;
DEFINES.CLUSTER_CLASS.LIGHTING.BALLAST_CONFIGURATION					= 0x0301;

DEFINES.CLUSTER_CLASS.HVAC.PUMP_CONFIGURATION_AND_CONTROL				= 0x0200;
DEFINES.CLUSTER_CLASS.HVAC.THERMOSTAT									= 0x0201;
DEFINES.CLUSTER_CLASS.HVAC.FAN_CONTROL									= 0x0202;
DEFINES.CLUSTER_CLASS.HVAC.DEHUMIDIFICATION_CONTROL						= 0x0203;
DEFINES.CLUSTER_CLASS.HVAC.THERMOSTAT_USER_INTERFACE_CONFIGURATION		= 0x0204;

DEFINES.CLUSTER_CLASS.MEASUREMENT_SENSING.ILLUMINANCE_MEASUREMENT		= 0x0400;
DEFINES.CLUSTER_CLASS.MEASUREMENT_SENSING.ILLUMINANCE_LEVEL_SENSING		= 0x0401;
DEFINES.CLUSTER_CLASS.MEASUREMENT_SENSING.TEMPERATURE_MEASUREMENT		= 0x0402;
DEFINES.CLUSTER_CLASS.MEASUREMENT_SENSING.PRESSURE_MEASUREMENT			= 0x0403;
DEFINES.CLUSTER_CLASS.MEASUREMENT_SENSING.FLOW_MEASUREMENT				= 0x0404;
DEFINES.CLUSTER_CLASS.MEASUREMENT_SENSING.RELATIVE_HUMIDITY_MEASUREMENT	= 0x0405;
DEFINES.CLUSTER_CLASS.MEASUREMENT_SENSING.OCCUPANCY_SENSING				= 0x0406;


DEFINES.WORK_CODE.ZCL_SEND_COMMAND					= 0x00;
DEFINES.WORK_CODE.ZCL_READ_ATTR						= 0x01;
DEFINES.WORK_CODE.ZCL_WRITE_ATTR					= 0x02;

DEFINES.SOURCE_ENDPOINT 							= 0x06;

DEFINES.ADDR_MODE.ADDR_NOT_PRESENT 					= 0;
DEFINES.ADDR_MODE.ADDR_GROUP 						= 1;
DEFINES.ADDR_MODE.ADDR_16BIT 						= 2; //only this is supported for now
DEFINES.ADDR_MODE.ADDR_64BIT 						= 3;
DEFINES.ADDR_MODE.ADDR_BROADCAST 					= 15;

DEFINES.DIRECTION.ZCL_FRAME_CLIENT_SERVER_DIR		= 0x00;
DEFINES.DIRECTION.ZCL_FRAME_SERVER_CLIENT_DIR		= 0x01;

DEFINES.DEVICETYPE= {
	0x00: "COORDINATOR",
	0x01: "ROUTER",
	0x02: "ENDDEVICE"
};

/*** Data Types ***/
//Length of data octets -- len = 0 means remaning payload is data, len = 0xff 
DEFINES.DATA_TYPE = {
	0x00: {"type": "ZCL_DATATYPE_NO_DATA", "len": 0},
	0x08: {"type": "ZCL_DATATYPE_DATA8", "len": 1},
	0x09: {"type": "ZCL_DATATYPE_DATA16", "len": 2},
	0x0a: {"type": "ZCL_DATATYPE_DATA24", "len": 3},
	0x0b: {"type": "ZCL_DATATYPE_DATA32", "len": 4},
	0x0c: {"type": "ZCL_DATATYPE_DATA40", "len": 5},
	0x0d: {"type": "ZCL_DATATYPE_DATA48", "len": 6},
	0x0e: {"type": "ZCL_DATATYPE_DATA56", "len": 7},
	0x0f: {"type": "ZCL_DATATYPE_DATA64", "len": 8},
	0x10: {"type": "ZCL_DATATYPE_BOOLEAN", "len": 1, "invalidNumber": 0xFF},
	0x18: {"type": "ZCL_DATATYPE_BITMAP8", "len": 1},
	0x19: {"type": "ZCL_DATATYPE_BITMAP16", "len": 2},
	0x1a: {"type": "ZCL_DATATYPE_BITMAP24", "len": 3},
	0x1b: {"type": "ZCL_DATATYPE_BITMAP32", "len": 4},
	0x1c: {"type": "ZCL_DATATYPE_BITMAP40", "len": 5},
	0x1d: {"type": "ZCL_DATATYPE_BITMAP48", "len": 6},
	0x1e: {"type": "ZCL_DATATYPE_BITMAP56", "len": 7},
	0x1f: {"type": "ZCL_DATATYPE_BITMAP64", "len": 8},
	0x20: {"type": "ZCL_DATATYPE_UINT8", "len": 1, "invalidNumber": 0xFF},
	0x21: {"type": "ZCL_DATATYPE_UINT16", "len": 2, "invalidNumber": 0xFFFF},
	0x22: {"type": "ZCL_DATATYPE_UINT24", "len": 3, "invalidNumber": 0xFFFFFF},
	0x23: {"type": "ZCL_DATATYPE_UINT32", "len": 4, "invalidNumber": 0xFFFFFFFF},
	0x24: {"type": "ZCL_DATATYPE_UINT40", "len": 5, "invalidNumber": 0xFFFFFFFFFF},
	0x25: {"type": "ZCL_DATATYPE_UINT48", "len": 6, "invalidNumber": 0xFFFFFFFFFFFF},
	0x26: {"type": "ZCL_DATATYPE_UINT56", "len": 7, "invalidNumber": 0xFFFFFFFFFFFFFF},
	0x27: {"type": "ZCL_DATATYPE_UINT64", "len": 8, "invalidNumber": 0xFFFFFFFFFFFFFFFF},
	0x28: {"type": "ZCL_DATATYPE_INT8", "len": 1, "invalidNumber": 0x80},
	0x29: {"type": "ZCL_DATATYPE_INT16", "len": 2, "invalidNumber": 0x8000},
	0x2a: {"type": "ZCL_DATATYPE_INT24", "len": 3, "invalidNumber": 0x800000},
	0x2b: {"type": "ZCL_DATATYPE_INT32", "len": 4, "invalidNumber": 0x80000000},
	0x2c: {"type": "ZCL_DATATYPE_INT40", "len": 5, "invalidNumber": 0x8000000000},
	0x2d: {"type": "ZCL_DATATYPE_INT48", "len": 6, "invalidNumber": 0x800000000000},
	0x2e: {"type": "ZCL_DATATYPE_INT56", "len": 7, "invalidNumber": 0x80000000000000},
	0x2f: {"type": "ZCL_DATATYPE_INT64", "len": 8, "invalidNumber": 0x8000000000000000},
	0x30: {"type": "ZCL_DATATYPE_ENUM8", "len": 1, "invalidNumber": 0xFF},
	0x31: {"type": "ZCL_DATATYPE_ENUM16", "len": 2, "invalidNumber": 0xFFFF},
	0x38: {"type": "ZCL_DATATYPE_SEMI_PREC", "len": 2},
	0x39: {"type": "ZCL_DATATYPE_SINGLE_PREC", "len": 4},
	0x3a: {"type": "ZCL_DATATYPE_DOUBLE_PREC", "len": 8},
	0x41: {"type": "ZCL_DATATYPE_OCTET_STR", "len": "1", "invalidNumber": 0xFF},
	0x42: {"type": "ZCL_DATATYPE_CHAR_STR", "len": "1", "invalidNumber": 0xFF},
	0x43: {"type": "ZCL_DATATYPE_LONG_OCTET_STR", "len": "2", "invalidNumber": 0xFFFF},
	0x44: {"type": "ZCL_DATATYPE_LONG_CHAR_STR", "len": "2", "invalidNumber": 0xFFFF},
	0x48: {"type": "ZCL_DATATYPE_ARRAY", "len": "2+", "invalidNumber": 0xFFFF},
	0x4c: {"type": "ZCL_DATATYPE_STRUCT", "len": "2+", "invalidNumber": 0xFFFF},
	0x50: {"type": "ZCL_DATATYPE_SET"},
	0x51: {"type": "ZCL_DATATYPE_BAG"},
	0xe0: {"type": "ZCL_DATATYPE_TOD", "len": 4, "invalidNumber": 0xFFFFFFFF},
	0xe1: {"type": "ZCL_DATATYPE_DATE", "len": 4, "invalidNumber": 0xFFFFFFFF},
	0xe2: {"type": "ZCL_DATATYPE_UTC", "len": 4, "invalidNumber": 0xFFFFFFFF},
	0xe8: {"type": "ZCL_DATATYPE_CLUSTER_ID", "len": 2, "invalidNumber": 0xFFFF},
	0xe9: {"type": "ZCL_DATATYPE_ATTR_ID", "len": 2, "invalidNumber": 0xFFFF},
	0xea: {"type": "ZCL_DATATYPE_BAC_OID", "len": 4, "invalidNumber": 0xFFFFFFFF},
	0xf0: {"type": "ZCL_DATATYPE_IEEE_ADDR", "len": 8, "invalidNumber": 0xFFFFFFFFFFFFFFFF},
	0xf1: {"type": "ZCL_DATATYPE_128_BIT_SEC_KEY", "len": 16},
	0xff: {"type": "ZCL_DATATYPE_UNKNOWN", "len": 0}
}

/*** Error Status Codes ***/
DEFINES.STATUS = {
	0x00 : "ZCL_STATUS_SUCCESS",
	0x01 : "ZCL_STATUS_FAILURE",
	0x7E : "ZCL_STATUS_NOT_AUTHORIZED",
	0x80 : "ZCL_STATUS_MALFORMED_COMMAND",
	0x81 : "ZCL_STATUS_UNSUP_CLUSTER_COMMAND",
	0x82 : "ZCL_STATUS_UNSUP_GENERAL_COMMAND",
	0x83 : "ZCL_STATUS_UNSUP_MANU_CLUSTER_COMMAND",
	0x84 : "ZCL_STATUS_UNSUP_MANU_GENERAL_COMMAND",
	0x85 : "ZCL_STATUS_INVALID_FIELD",
	0x86 : "ZCL_STATUS_UNSUPPORTED_ATTRIBUTE",
	0x87 : "ZCL_STATUS_INVALID_VALUE",
	0x88 : "ZCL_STATUS_READ_ONLY",
	0x89 : "ZCL_STATUS_INSUFFICIENT_SPACE",
	0x8a : "ZCL_STATUS_DUPLICATE_EXISTS",
	0x8b : "ZCL_STATUS_NOT_FOUND",
	0x8c : "ZCL_STATUS_UNREPORTABLE_ATTRIBUTE",
	0x8d : "ZCL_STATUS_INVALID_DATA_TYPE",
	0x8e : "ZCL_STATUS_INVALID_SELECTOR",
	0x8f : "ZCL_STATUS_WRITE_ONLY",
	0x90 : "ZCL_STATUS_INCONSISTENT_STARTUP_STATE",
	0x91 : "ZCL_STATUS_DEFINED_OUT_OF_BAND",
	0x92 : "ZCL_STATUS_INCONSISTENT",
	0x93 : "ZCL_STATUS_ACTION_DENIED",
	0x94 : "ZCL_STATUS_TIMEOUT",
	0x95 : "ZCL_STATUS_ABORT",
	0x96 : "ZCL_STATUS_INVALID_IMAGE",
	0x97 : "ZCL_STATUS_WAIT_FOR_DATA",
	0x98 : "ZCL_STATUS_NO_IMAGE_AVAILABLE",
	0x99 : "ZCL_STATUS_REQUIRE_MORE_IMAGE",
	0xc0 : "ZCL_STATUS_HARDWARE_FAILURE",
	0xc1 : "ZCL_STATUS_SOFTWARE_FAILURE",
	0xc2 : "ZCL_STATUS_CALIBRATION_ERROR",
	0xFF : "ZCL_STATUS_CMD_HAS_RSP"
}


//TI CC2530 ZNP Stack NV Items 
//Reference- mtSys.h
// OSAL NV item IDs
DEFINES.NV_ITEM_ID.EXTADDR                   = 0x0001;
DEFINES.NV_ITEM_ID.BOOTCOUNTER               = 0x0002;
DEFINES.NV_ITEM_ID.STARTUP_OPTION            = 0x0003;
DEFINES.NV_ITEM_ID.START_DELAY               = 0x0004;
DEFINES.NV_ITEM_ID.NIB                       = 0x0021;
DEFINES.NV_ITEM_ID.DEVICE_LIST               = 0x0022;
DEFINES.NV_ITEM_ID.ADDRMGR                   = 0x0023;
DEFINES.NV_ITEM_ID.POLL_RATE                 = 0x0024;
DEFINES.NV_ITEM_ID.QUEUED_POLL_RATE          = 0x0025;
DEFINES.NV_ITEM_ID.RESPONSE_POLL_RATE        = 0x0026;
DEFINES.NV_ITEM_ID.REJOIN_POLL_RATE          = 0x0027;
DEFINES.NV_ITEM_ID.DATA_RETRIES              = 0x0028;
DEFINES.NV_ITEM_ID.POLL_FAILURE_RETRIES      = 0x0029;
DEFINES.NV_ITEM_ID.STACK_PROFILE             = 0x002A;
DEFINES.NV_ITEM_ID.INDIRECT_MSG_TIMEOUT      = 0x002B;
DEFINES.NV_ITEM_ID.ROUTE_EXPIRY_TIME         = 0x002C;
DEFINES.NV_ITEM_ID.EXTENDED_PAN_ID           = 0x002D;
DEFINES.NV_ITEM_ID.BCAST_RETRIES             = 0x002E;
DEFINES.NV_ITEM_ID.PASSIVE_ACK_TIMEOUT       = 0x002F;
DEFINES.NV_ITEM_ID.BCAST_DELIVERY_TIME       = 0x0030;
DEFINES.NV_ITEM_ID.NWK_MODE                  = 0x0031;
DEFINES.NV_ITEM_ID.CONCENTRATOR_ENABLE       = 0x0032;
DEFINES.NV_ITEM_ID.CONCENTRATOR_DISCOVERY    = 0x0033;
DEFINES.NV_ITEM_ID.CONCENTRATOR_RADIUS       = 0x0034;
DEFINES.NV_ITEM_ID.CONCENTRATOR_RC           = 0x0036;
DEFINES.NV_ITEM_ID.NWK_MGR_MODE              = 0x0037;
DEFINES.NV_ITEM_ID.SRC_RTG_EXPIRY_TIME       = 0x0038;
DEFINES.NV_ITEM_ID.ROUTE_DISCOVERY_TIME      = 0x0039;
DEFINES.NV_ITEM_ID.NWK_ACTIVE_KEY_INFO       = 0x003A;
DEFINES.NV_ITEM_ID.NWK_ALTERN_KEY_INFO       = 0x003B;
DEFINES.NV_ITEM_ID.ROUTER_OFF_ASSOC_CLEANUP  = 0x003C;
DEFINES.NV_ITEM_ID.NWK_LEAVE_REQ_ALLOWED     = 0x003D;
DEFINES.NV_ITEM_ID.NWK_CHILD_AGE_ENABLE      = 0x003E;
DEFINES.NV_ITEM_ID.DEVICE_LIST_KA_TIMEOUT    = 0x003F;
DEFINES.NV_ITEM_ID.BINDING_TABLE             = 0x0041;
DEFINES.NV_ITEM_ID.GROUP_TABLE               = 0x0042;
DEFINES.NV_ITEM_ID.APS_FRAME_RETRIES         = 0x0043;
DEFINES.NV_ITEM_ID.APS_ACK_WAIT_DURATION     = 0x0044;
DEFINES.NV_ITEM_ID.APS_ACK_WAIT_MULTIPLIER   = 0x0045;
DEFINES.NV_ITEM_ID.BINDING_TIME              = 0x0046;
DEFINES.NV_ITEM_ID.APS_USE_EXT_PANID         = 0x0047;
DEFINES.NV_ITEM_ID.APS_USE_INSECURE_JOIN     = 0x0048;
DEFINES.NV_ITEM_ID.COMMISSIONED_NWK_ADDR     = 0x0049;
DEFINES.NV_ITEM_ID.APS_NONMEMBER_RADIUS      = 0x004B;
DEFINES.NV_ITEM_ID.APS_LINK_KEY_TABLE        = 0x004C;
DEFINES.NV_ITEM_ID.APS_DUPREJ_TIMEOUT_INC    = 0x004D;
DEFINES.NV_ITEM_ID.APS_DUPREJ_TIMEOUT_COUNT  = 0x004E;
DEFINES.NV_ITEM_ID.APS_DUPREJ_TABLE_SIZE     = 0x004F;
DEFINES.NV_ITEM_ID.SECURITY_LEVEL            = 0x0061;
DEFINES.NV_ITEM_ID.PRECFGKEY                 = 0x0062;
DEFINES.NV_ITEM_ID.PRECFGKEYS_ENABLE         = 0x0063;
DEFINES.NV_ITEM_ID.SECURITY_MODE             = 0x0064;
DEFINES.NV_ITEM_ID.SECURE_PERMIT_JOIN        = 0x0065;
DEFINES.NV_ITEM_ID.APS_LINK_KEY_TYPE         = 0x0066;
DEFINES.NV_ITEM_ID.APS_ALLOW_R19_SECURITY    = 0x0067;
DEFINES.NV_ITEM_ID.IMPLICIT_CERTIFICATE      = 0x0069;
DEFINES.NV_ITEM_ID.DEVICE_PRIVATE_KEY        = 0x006A;
DEFINES.NV_ITEM_ID.CA_PUBLIC_KEY             = 0x006B;
DEFINES.NV_ITEM_ID.USE_DEFAULT_TCLK          = 0x006D;
DEFINES.NV_ITEM_ID.TRUSTCENTER_ADDR          = 0x006E;
DEFINES.NV_ITEM_ID.RNG_COUNTER               = 0x006F;
DEFINES.NV_ITEM_ID.RANDOM_SEED               = 0x0070;
DEFINES.NV_ITEM_ID.USERDESC                  = 0x0081;
DEFINES.NV_ITEM_ID.NWKKEY                    = 0x0082;
DEFINES.NV_ITEM_ID.PANID                     = 0x0083;
DEFINES.NV_ITEM_ID.CHANLIST                  = 0x0084;
DEFINES.NV_ITEM_ID.LEAVE_CTRL                = 0x0085;
DEFINES.NV_ITEM_ID.SCAN_DURATION             = 0x0086;
DEFINES.NV_ITEM_ID.LOGICAL_TYPE              = 0x0087;
DEFINES.NV_ITEM_ID.NWKMGR_MIN_TX             = 0x0088;
DEFINES.NV_ITEM_ID.NWKMGR_ADDR               = 0x0089;
DEFINES.NV_ITEM_ID.ZDO_DIRECT_CB             = 0x008F;
DEFINES.NV_ITEM_ID.SCENE_TABLE               = 0x0091;
DEFINES.NV_ITEM_ID.MIN_FREE_NWK_ADDR         = 0x0092;
DEFINES.NV_ITEM_ID.MAX_FREE_NWK_ADDR         = 0x0093;
DEFINES.NV_ITEM_ID.MIN_FREE_GRP_ID           = 0x0094;
DEFINES.NV_ITEM_ID.MAX_FREE_GRP_ID           = 0x0095;
DEFINES.NV_ITEM_ID.MIN_GRP_IDS               = 0x0096;
DEFINES.NV_ITEM_ID.MAX_GRP_IDS               = 0x0097;
DEFINES.NV_ITEM_ID.SAPI_ENDPOINT             = 0x00A1;
DEFINES.NV_ITEM_ID.SAS_SHORT_ADDR            = 0x00B1;
DEFINES.NV_ITEM_ID.SAS_EXT_PANID             = 0x00B2;
DEFINES.NV_ITEM_ID.SAS_PANID                 = 0x00B3;
DEFINES.NV_ITEM_ID.SAS_CHANNEL_MASK          = 0x00B4;
DEFINES.NV_ITEM_ID.SAS_PROTOCOL_VER          = 0x00B5;
DEFINES.NV_ITEM_ID.SAS_STACK_PROFILE         = 0x00B6;
DEFINES.NV_ITEM_ID.SAS_STARTUP_CTRL          = 0x00B7;
DEFINES.NV_ITEM_ID.SAS_TC_ADDR               = 0x00C1;
DEFINES.NV_ITEM_ID.SAS_TC_MASTER_KEY         = 0x00C2;
DEFINES.NV_ITEM_ID.SAS_NWK_KEY               = 0x00C3;
DEFINES.NV_ITEM_ID.SAS_USE_INSEC_JOIN        = 0x00C4;
DEFINES.NV_ITEM_ID.SAS_PRECFG_LINK_KEY       = 0x00C5;
DEFINES.NV_ITEM_ID.SAS_NWK_KEY_SEQ_NUM       = 0x00C6;
DEFINES.NV_ITEM_ID.SAS_NWK_KEY_TYPE          = 0x00C7;
DEFINES.NV_ITEM_ID.SAS_NWK_MGR_ADDR          = 0x00C8;
DEFINES.NV_ITEM_ID.SAS_CURR_TC_MASTER_KEY    = 0x00D1;
DEFINES.NV_ITEM_ID.SAS_CURR_NWK_KEY          = 0x00D2;
DEFINES.NV_ITEM_ID.SAS_CURR_PRECFG_LINK_KEY  = 0x00D3;
DEFINES.NV_ITEM_ID.TCLK_TABLE_START          = 0x0101;
DEFINES.NV_ITEM_ID.TCLK_TABLE_END            = 0x01FF;
DEFINES.NV_ITEM_ID.APS_LINK_KEY_DATA_START   = 0x0201;
DEFINES.NV_ITEM_ID.APS_LINK_KEY_DATA_END     = 0x02FF;
DEFINES.NV_ITEM_ID.MASTER_KEY_DATA_START     = 0x0301;
DEFINES.NV_ITEM_ID.MASTER_KEY_DATA_END       = 0x03FF;

module.exports = {
	DEFINES: DEFINES
};